netty:
  port: 7878
server:
  port: 9010
  servlet:
    context-path: /
  tomcat:
    basedir: /tmp/tomcat

delay: -30

spring:
  datasource:
    url: jdbc:mysql://47.111.27.169:3306/haoyidatabase?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: qcxk@#123QCXK
    # Hikari
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 空闲连接的最小数量
      minimum-idle: 10
      # 连接池最大连接数
      maximum-pool-size: 80
      # 自动提交
      auto-commit: true
      # 连接idle状态的最大时长（毫秒）
      idle-timeout: 30000
      # 连接池名称（可改）
      pool-name: springHikariCP
      # 连接的生命时长（毫秒）
      max-lifetime: 1800000
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 30000
      # 用来检测连接是否有效
      connection-test-query: SELECT 1
      # 是否是只读数据源, 做读写分离时有用, 保证slave数据源的安全
      read-only: false
    main:
      allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qcxk.model
  #开启MyBatis的二级缓存
  configuration.cache-enabled: true

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  params: count=countSql
  supportMethodsArguments: true