FROM centos:7 

ARG version=v2.3
ARG agent_work_path=/data/kbdp/dts/dts-executor

# Environments
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
#ENV JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk

# jdk 安装 切换到usr/local 目录下
WORKDIR /usr/local
 # 创建jdk目录
RUN mkdir jdk
# 对jdk赋权
RUN chmod 777 /usr/local/jdk
# 将下载的jdk 的压缩包拷贝到镜像中，注意 ADD和COPY的区别，ADD 会解压，COPY不会解压
ADD jdk1.8.0_211.tar.gz /usr/local/jdk
# 设置JAVA_HOME 的环境变量
ENV JAVA_HOME /usr/local/jdk/1.8.0_211
ENV JRE_HOME ${JAVA_HOME}/jre
ENV CLASSPATH=$JAVA_HOME/bin:$JAVA_HOME/lib:$JAVA_HOME/jre/lib
# 将java可执行文件设置到PATH中，这样就可以使用java命令了
ENV	PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH

# Labels
LABEL dts.version=${version}

# Working directory 
WORKDIR ${agent_work_path} 

# Add dts agent
ADD dts-job-agent-1.0-SNAPSHOT.tar .


# 开始构建
RUN set -ex &&\

    # Install GCC for compile execute-as-user.c 
    yum install -y gcc &&\
    
    # Install sudo for user dts
    yum install -y sudo &&\

    # Install java8
    #yum install -y java-1.8.0-openjdk &&\

    # Process Dts agent evnironment 
    cp -rf dts-job-agent-1.0-SNAPSHOT/* ./ &&\
    rm -rf dts-job-agent-1.0-SNAPSHOT &&\
    ln -sf /data/kbdp/dts/dts-executor/bin/launch.sh /usr/local/bin/runjob  &&\
    ln -sf /data/kbdp/dts/dts-executor/bin/launch_job_resource.sh /usr/local/bin/runresourcejob  &&\
    cd native && gcc -o executor-as-user execute-as-user.c &&\

    # Set TimeZone 
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&\
    echo 'Asia/Shanghai' >/etc/timezone  &&\ 

    # Install python3/pip/pip3 （python2 is installed by centos already ） 
    yum -y install epel-release &&\
    yum -y install https://mirrors.tongji.edu.cn/ius/7/x86_64/packages/i/ius-release-2-1.el7.ius.noarch.rpm  &&\
    yum -y install python-pip &&\
    yum -y install python36u &&\
    yum -y install python36u-pip &&\
    ln -sf /usr/bin/python3.6 /usr/bin/python3 &&\
    ln -sf /usr/bin/pip3.6 /usr/bin/pip3 &&\

    # Change worksapce to user dts 
    useradd --create-home --no-log-init --shell /bin/bash dts &&\
    chown -R dts:dts /data &&\
    chmod -R 755 /data &&\
    chown dts:dts /usr/local/bin/runjob &&\
    chown dts:dts /usr/local/bin/runresourcejob &&\
    chmod 755 /usr/local/bin/runjob &&\
    chmod 755 /usr/local/bin/runresourcejob &&\
    mkdir -p /etc/security/keytabs &&\
    chmod -R 777 /etc/security/keytabs &&\
    echo "dts ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

    # Clean yum cache
    #yum -y clean all 

# Change user to dts
# USER dts

# Change working directory to plugins
WORKDIR ${agent_work_path}/plugins
